#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

mkdir -p "$PROJECT_ROOT/assets/badges"
pushd "$PROJECT_ROOT/assets/badges"

declare -A badges
badges=(
    [unknown.svg]="https://img.shields.io/badge/Integration-Unknown-lightgrey.svg"
    [unknown_v2.svg]="https://img.shields.io/badge/automatic_tests_level-unknown-lightgrey.svg?style=for-the-badge"
    [empty.svg]="https://upload.wikimedia.org/wikipedia/commons/1/1d/No_image.svg"
    [unmaintained.svg]="https://img.shields.io/badge/Status-Package%20not%20maintained-red.svg"
    [state-working.svg]="https://img.shields.io/badge/Status-working-brightgreen.svg"
    [state-just-got-added-to-catalog.svg]="https://img.shields.io/badge/Status-Just%20got%20added%20to%20catalog-yellowgreen.svg"
    [state-inprogress.svg]="https://img.shields.io/badge/Status-In%20progress-orange.svg"
    [state-notworking.svg]="https://img.shields.io/badge/Status-Not%20working-red.svg"
    [state-broken.svg]="https://img.shields.io/badge/Status-Broken-red.svg"

    [level0.svg]="https://img.shields.io/badge/Integration-Level_0-red.svg"
    [level1.svg]="https://img.shields.io/badge/Integration-Level_1-orange.svg"
    [level2.svg]="https://img.shields.io/badge/Integration-Level_2-orange.svg"
    [level3.svg]="https://img.shields.io/badge/Integration-Level_3-yellow.svg"
    [level4.svg]="https://img.shields.io/badge/Integration-Level_4-yellow.svg"
    [level5.svg]="https://img.shields.io/badge/Integration-Level_5-yellowgreen.svg"
    [level6.svg]="https://img.shields.io/badge/Integration-Level_6-yellowgreen.svg"
    [level7.svg]="https://img.shields.io/badge/Integration-Level_7-green.svg"
    [level8.svg]="https://img.shields.io/badge/Integration-Level_8-brightgreen.svg"
    [level9.svg]="https://img.shields.io/badge/Integration-Level_9-blue.svg"
    [level0_v2.svg]="https://img.shields.io/badge/automatic_tests_level-0-red.svg?style=for-the-badge"
    [level1_v2.svg]="https://img.shields.io/badge/automatic_tests_level-1-orange.svg?style=for-the-badge"
    [level2_v2.svg]="https://img.shields.io/badge/automatic_tests_level-2-orange.svg?style=for-the-badge"
    [level3_v2.svg]="https://img.shields.io/badge/automatic_tests_level-3-yellow.svg?style=for-the-badge"
    [level4_v2.svg]="https://img.shields.io/badge/automatic_tests_level-4-yellow.svg?style=for-the-badge"
    [level5_v2.svg]="https://img.shields.io/badge/automatic_tests_level-5-yellowgreen.svg?style=for-the-badge"
    [level6_v2.svg]="https://img.shields.io/badge/automatic_tests_level-6-yellowgreen.svg?style=for-the-badge"
    [level7_v2.svg]="https://img.shields.io/badge/automatic_tests_level-7-green.svg?style=for-the-badge"
    [level8_v2.svg]="https://img.shields.io/badge/automatic_tests_level-8-brightgreen.svg?style=for-the-badge"
    [level9_v2.svg]="https://img.shields.io/badge/automatic_tests_level-9-blue.svg?style=for-the-badge"
)

echo "Fetching badges..."
for badge in "${!badges[@]}"; do
    curl --no-progress-meter -o "$badge" "${badges[$badge]}"
done
